/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'IT000531' at '14/12/16 11:21 PM' with Gradle 2.14.1
 *
 * @author IT000531, @date 14/12/16 11:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
